# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'COMMONMenu.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True) #enable highdpi scaling
QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps, True) #use highdpi icons

class Ui_HotelMenu(object):
    def setupUi(self, HotelMenu):
        HotelMenu.setObjectName("HotelMenu")
        HotelMenu.resize(450, 470)
        HotelMenu.setMinimumSize(QtCore.QSize(450, 470))
        HotelMenu.setMaximumSize(QtCore.QSize(450, 470))
        self.centralwidget = QtWidgets.QWidget(HotelMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.labelMain = QtWidgets.QLabel(self.centralwidget)
        self.labelMain.setGeometry(QtCore.QRect(270, 100, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft Yi Baiti")
        font.setPointSize(26)
        self.labelMain.setFont(font)
        self.labelMain.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMain.setObjectName("labelMain")
        self.frameManager = QtWidgets.QFrame(self.centralwidget)
        self.frameManager.setGeometry(QtCore.QRect(0, 10, 231, 251))
        self.frameManager.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameManager.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameManager.setObjectName("frameManager")
        self.rateSpin_L = QtWidgets.QDoubleSpinBox(self.frameManager)
        self.rateSpin_L.setGeometry(QtCore.QRect(140, 190, 41, 20))
        self.rateSpin_L.setDecimals(1)
        self.rateSpin_L.setMinimum(0.5)
        self.rateSpin_L.setMaximum(10.0)
        self.rateSpin_L.setSingleStep(0.5)
        self.rateSpin_L.setObjectName("rateSpin_L")
        self.PowerButton = QtWidgets.QPushButton(self.frameManager)
        self.PowerButton.setGeometry(QtCore.QRect(150, 20, 56, 17))
        self.PowerButton.setObjectName("PowerButton")
        self.PowerLabel = QtWidgets.QLabel(self.frameManager)
        self.PowerLabel.setGeometry(QtCore.QRect(20, 20, 71, 16))
        self.PowerLabel.setObjectName("PowerLabel")
        self.line = QtWidgets.QFrame(self.frameManager)
        self.line.setGeometry(QtCore.QRect(20, 50, 191, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.tempSpin_min = QtWidgets.QSpinBox(self.frameManager)
        self.tempSpin_min.setGeometry(QtCore.QRect(130, 100, 31, 16))
        self.tempSpin_min.setMinimum(16)
        self.tempSpin_min.setMaximum(28)
        self.tempSpin_min.setObjectName("tempSpin_min")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frameManager)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 70, 81, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelMode_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelMode_2.setObjectName("labelMode_2")
        self.verticalLayout_2.addWidget(self.labelMode_2)
        self.label_Range_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_Range_2.setObjectName("label_Range_2")
        self.verticalLayout_2.addWidget(self.label_Range_2)
        self.label_rateH_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_rateH_2.setObjectName("label_rateH_2")
        self.verticalLayout_2.addWidget(self.label_rateH_2)
        self.label_rateM_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_rateM_2.setObjectName("label_rateM_2")
        self.verticalLayout_2.addWidget(self.label_rateM_2)
        self.label_rateL_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_rateL_2.setObjectName("label_rateL_2")
        self.verticalLayout_2.addWidget(self.label_rateL_2)
        self.rateSpin_H = QtWidgets.QDoubleSpinBox(self.frameManager)
        self.rateSpin_H.setGeometry(QtCore.QRect(140, 130, 41, 20))
        self.rateSpin_H.setDecimals(1)
        self.rateSpin_H.setMinimum(0.5)
        self.rateSpin_H.setMaximum(10.0)
        self.rateSpin_H.setSingleStep(0.5)
        self.rateSpin_H.setObjectName("rateSpin_H")
        self.rateSpin_M = QtWidgets.QDoubleSpinBox(self.frameManager)
        self.rateSpin_M.setGeometry(QtCore.QRect(140, 160, 41, 20))
        self.rateSpin_M.setDecimals(1)
        self.rateSpin_M.setMinimum(0.5)
        self.rateSpin_M.setMaximum(10.0)
        self.rateSpin_M.setSingleStep(0.5)
        self.rateSpin_M.setObjectName("rateSpin_M")
        self.to_label = QtWidgets.QLabel(self.frameManager)
        self.to_label.setGeometry(QtCore.QRect(166, 100, 20, 20))
        self.to_label.setObjectName("to_label")
        self.ModeButton = QtWidgets.QPushButton(self.frameManager)
        self.ModeButton.setGeometry(QtCore.QRect(150, 70, 56, 17))
        self.ModeButton.setObjectName("ModeButton")
        self.rmb_C_label2 = QtWidgets.QLabel(self.frameManager)
        self.rmb_C_label2.setGeometry(QtCore.QRect(190, 160, 21, 16))
        self.rmb_C_label2.setObjectName("rmb_C_label2")
        self.tempSpin_max = QtWidgets.QSpinBox(self.frameManager)
        self.tempSpin_max.setGeometry(QtCore.QRect(180, 100, 31, 16))
        self.tempSpin_max.setMinimum(16)
        self.tempSpin_max.setMaximum(28)
        self.tempSpin_max.setProperty("value", 28)
        self.tempSpin_max.setObjectName("tempSpin_max")
        self.rmb_C_label1 = QtWidgets.QLabel(self.frameManager)
        self.rmb_C_label1.setGeometry(QtCore.QRect(190, 130, 21, 16))
        self.rmb_C_label1.setObjectName("rmb_C_label1")
        self.rmb_C_label3 = QtWidgets.QLabel(self.frameManager)
        self.rmb_C_label3.setGeometry(QtCore.QRect(190, 190, 21, 16))
        self.rmb_C_label3.setObjectName("rmb_C_label3")
        self.ConfirmButton_2 = QtWidgets.QPushButton(self.frameManager)
        self.ConfirmButton_2.setGeometry(QtCore.QRect(20, 220, 189, 17))
        self.ConfirmButton_2.setObjectName("ConfirmButton_2")
        self.groupBox_manager = QtWidgets.QGroupBox(self.frameManager)
        self.groupBox_manager.setGeometry(QtCore.QRect(10, 0, 211, 251))
        self.groupBox_manager.setObjectName("groupBox_manager")
        self.groupBox_manager.raise_()
        self.rateSpin_L.raise_()
        self.PowerButton.raise_()
        self.PowerLabel.raise_()
        self.line.raise_()
        self.tempSpin_min.raise_()
        self.verticalLayoutWidget.raise_()
        self.rateSpin_H.raise_()
        self.rateSpin_M.raise_()
        self.to_label.raise_()
        self.ModeButton.raise_()
        self.rmb_C_label2.raise_()
        self.tempSpin_max.raise_()
        self.rmb_C_label1.raise_()
        self.rmb_C_label3.raise_()
        self.ConfirmButton_2.raise_()
        self.frameReception = QtWidgets.QFrame(self.centralwidget)
        self.frameReception.setGeometry(QtCore.QRect(0, 260, 231, 211))
        self.frameReception.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameReception.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameReception.setObjectName("frameReception")
        self.textBrowser_reception = QtWidgets.QTextBrowser(self.frameReception)
        self.textBrowser_reception.setGeometry(QtCore.QRect(20, 31, 191, 91))
        self.textBrowser_reception.setObjectName("textBrowser_reception")
        self.layoutWidget = QtWidgets.QWidget(self.frameReception)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 130, 191, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.InvoiceButton = QtWidgets.QPushButton(self.frameReception)
        self.InvoiceButton.setGeometry(QtCore.QRect(21, 152, 189, 17))
        self.InvoiceButton.setObjectName("InvoiceButton")
        self.RDRbutton = QtWidgets.QPushButton(self.frameReception)
        self.RDRbutton.setGeometry(QtCore.QRect(21, 131, 189, 17))
        self.RDRbutton.setObjectName("RDRbutton")
        self.RDRPrintButton = QtWidgets.QPushButton(self.frameReception)
        self.RDRPrintButton.setGeometry(QtCore.QRect(21, 173, 189, 17))
        self.RDRPrintButton.setObjectName("RDRPrintButton")
        self.groupBox_reception = QtWidgets.QGroupBox(self.frameReception)
        self.groupBox_reception.setGeometry(QtCore.QRect(10, 10, 211, 191))
        self.groupBox_reception.setObjectName("groupBox_reception")
        self.groupBox_reception.raise_()
        self.textBrowser_reception.raise_()
        self.layoutWidget.raise_()
        self.InvoiceButton.raise_()
        self.RDRbutton.raise_()
        self.RDRPrintButton.raise_()
        self.frameAdmin = QtWidgets.QFrame(self.centralwidget)
        self.frameAdmin.setGeometry(QtCore.QRect(240, 210, 211, 251))
        self.frameAdmin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameAdmin.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameAdmin.setObjectName("frameAdmin")
        self.textBrowser_admin = QtWidgets.QTextBrowser(self.frameAdmin)
        self.textBrowser_admin.setGeometry(QtCore.QRect(10, 40, 181, 121))
        self.textBrowser_admin.setObjectName("textBrowser_admin")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frameAdmin)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 170, 181, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.ButtonMonth = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ButtonMonth.setObjectName("ButtonMonth")
        self.gridLayout.addWidget(self.ButtonMonth, 1, 0, 1, 1)
        self.ButtonWeek = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ButtonWeek.setObjectName("ButtonWeek")
        self.gridLayout.addWidget(self.ButtonWeek, 0, 1, 1, 1)
        self.ButtonYear = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ButtonYear.setObjectName("ButtonYear")
        self.gridLayout.addWidget(self.ButtonYear, 1, 1, 1, 1)
        self.ButtonDaily = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ButtonDaily.setObjectName("ButtonDaily")
        self.gridLayout.addWidget(self.ButtonDaily, 0, 0, 1, 1)
        self.ButtonPrint = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ButtonPrint.setObjectName("ButtonPrint")
        self.gridLayout.addWidget(self.ButtonPrint, 2, 0, 1, 1)
        self.groupBox_admin = QtWidgets.QGroupBox(self.frameAdmin)
        self.groupBox_admin.setGeometry(QtCore.QRect(0, 10, 201, 241))
        self.groupBox_admin.setObjectName("groupBox_admin")
        self.groupBox_admin.raise_()
        self.textBrowser_admin.raise_()
        self.gridLayoutWidget.raise_()
        self.spinID = QtWidgets.QSpinBox(self.centralwidget)
        self.spinID.setGeometry(QtCore.QRect(250, 30, 191, 19))
        self.spinID.setMinimum(1)
        self.spinID.setMaximum(5)
        self.spinID.setObjectName("spinID")
        self.labelID = QtWidgets.QLabel(self.centralwidget)
        self.labelID.setGeometry(QtCore.QRect(250, 10, 191, 16))
        self.labelID.setObjectName("labelID")
        HotelMenu.setCentralWidget(self.centralwidget)

        self.retranslateUi(HotelMenu)
        QtCore.QMetaObject.connectSlotsByName(HotelMenu)

    def retranslateUi(self, HotelMenu):
        _translate = QtCore.QCoreApplication.translate
        HotelMenu.setWindowTitle(_translate("HotelMenu", "Hotel Menu"))
        self.labelMain.setText(_translate("HotelMenu", "ACC SYSTEM"))
        self.PowerButton.setText(_translate("HotelMenu", "Switch"))
        self.PowerLabel.setText(_translate("HotelMenu", "Power state: ON"))
        self.labelMode_2.setText(_translate("HotelMenu", "Mode: Winter"))
        self.label_Range_2.setText(_translate("HotelMenu", "Temperature range"))
        self.label_rateH_2.setText(_translate("HotelMenu", "Fee rate (High)"))
        self.label_rateM_2.setText(_translate("HotelMenu", "Fee rate (Medium)"))
        self.label_rateL_2.setText(_translate("HotelMenu", "Fee rate (Low)"))
        self.to_label.setText(_translate("HotelMenu", "to"))
        self.ModeButton.setText(_translate("HotelMenu", "Switch"))
        self.rmb_C_label2.setText(_translate("HotelMenu", "元/1C°"))
        self.rmb_C_label1.setText(_translate("HotelMenu", "元/1C°"))
        self.rmb_C_label3.setText(_translate("HotelMenu", "元/1C°"))
        self.ConfirmButton_2.setText(_translate("HotelMenu", "Confirm"))
        self.groupBox_manager.setTitle(_translate("HotelMenu", "Manager"))
        self.textBrowser_reception.setHtml(_translate("MainWindowR", "Invoice/RDR:"))
        self.InvoiceButton.setText(_translate("HotelMenu", "Invoice"))
        self.RDRbutton.setText(_translate("HotelMenu", "Detailed record"))
        self.RDRPrintButton.setText(_translate("HotelMenu", "Print detailed record"))
        self.groupBox_reception.setTitle(_translate("HotelMenu", "Reception"))
        self.ButtonMonth.setText(_translate("HotelMenu", "Month report"))
        self.ButtonWeek.setText(_translate("HotelMenu", "Week report"))
        self.ButtonYear.setText(_translate("HotelMenu", "Year report"))
        self.ButtonDaily.setText(_translate("HotelMenu", "Daily report"))
        self.ButtonPrint.setText(_translate("HotelMenu", "Print"))
        self.groupBox_admin.setTitle(_translate("HotelMenu", "Administrator"))
        self.labelID.setText(_translate("HotelMenu", "Room ID"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HotelMenu = QtWidgets.QMainWindow()
    ui = Ui_HotelMenu()
    ui.setupUi(HotelMenu)
    HotelMenu.show()
    sys.exit(app.exec_())
